# This is a basic workflow to help you get started with Actions

name: Windows C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc -Wall -c 3_Implementation/src/ResetScore.c
           gcc -Wall -c 3_Implementation/src/HighestScore.c
           gcc -Wall -c 3_Implementation/src/ShowLandingPage.c 
           gcc -Wall -c 3_Implementation/src/main.c    
           gcc -o main Help.o HighestScore.o ResetScore.o ShowLandingPage.o main.o
    - name: Run
      run: .\main.exe
